export interface LocalityData {
  slug: string;
  name: string;
  zone: 'Central Core' | 'North Zone' | 'South Zone' | 'East Zone' | 'West Zone';
  zoneSlug: 'central' | 'north' | 'south' | 'east' | 'west';
  pincode: string;
  tagline: string;
  overview: string;
  bylawAuthority: string;
  farAndSetbacks: string;
  soilAndFoundation: string;
  waterAndBorewell: string;
  popularStyles: string[];
  avgCostPerSqFt: {
    essential: number;
    executive: number;
    luxury: number;
  };
  keyLandmarks: string[];
  faqs: {
    question: string;
    answer: string;
  }[];
}

export interface BengaluruZoneInfo {
  name: string;
  slug: 'central' | 'north' | 'south' | 'east' | 'west';
  badge?: string;
  description: string;
  localities: string[];
}

export const BENGALURU_ZONES_DATA: BengaluruZoneInfo[] = [
  {
    name: 'Central Core',
    slug: 'central',
    badge: 'Primary Focus',
    description: 'Heritage bungalows, luxury villa re-developments, and bespoke architectural homes with historic colonial charm.',
    localities: [
      'Lavelle Road', 'Richmond Town', 'MG Road', 'Cunningham Road',
      'Vasanth Nagar', 'Sadashivanagar', 'Malleshwaram', 'Frazer Town',
      'Cox Town', 'Benson Town', 'Cooke Town', 'Ulsoor',
      'Shanthi Nagar', 'Langford Town', 'Victoria Layout', 'Ashok Nagar',
    ],
  },
  {
    name: 'North Zone',
    slug: 'north',
    description: 'Airport corridor residences, gated luxury villa communities, and high-growth plotted layouts.',
    localities: [
      'Hebbal', 'Yelahanka', 'Jakkur', 'Sahakar Nagar', 'Thanisandra',
      'Hennur Road', 'Devanahalli', 'Manyata Tech Park', 'Vidyaranyapura',
      'RMV Extension', 'RT Nagar', 'Sanjaynagar', 'Bellary Road',
      'Kogilu', 'Doddaballapur Road',
    ],
  },
  {
    name: 'South Zone',
    slug: 'south',
    description: 'Established residential localities, independent multi-generational duplexes, and tech corridor villas.',
    localities: [
      'Koramangala', 'HSR Layout', 'Jayanagar', 'JP Nagar', 'BTM Layout',
      'Bannerghatta Road', 'Electronic City', 'Kanakapura Road', 'Padmanabhanagar',
      'Banashankari', 'Harlur Road', 'Kasavanahalli', 'Uttarahalli',
      'Begur', 'Gottigere',
    ],
  },
  {
    name: 'East Zone',
    slug: 'east',
    description: 'IT hub residences, contemporary architectural villas, and luxury gated township properties.',
    localities: [
      'Indiranagar', 'Whitefield', 'Sarjapur Road', 'Bellandur', 'Marathahalli',
      'Varthur', 'CV Raman Nagar', 'Mahadevapura', 'KR Puram',
      'Brookefield', 'Hoodi', 'Kadugodi', 'Domlur', 'Panathur',
      'Budigere Cross',
    ],
  },
  {
    name: 'West Zone',
    slug: 'west',
    description: 'Traditional family estates, Vaastu-optimized multi-level duplexes, and commercial mixed-use developments.',
    localities: [
      'Rajajinagar', 'Basavanagudi', 'Vijayanagar', 'Nagarbhavi',
      'Yeshwanthpur', 'Mahalakshmi Layout', 'RR Nagar', 'Kengeri',
      'Chandra Layout', 'Peenya', 'Magadi Road', 'Mallathahalli',
      'Subramanyapura', 'Ullal', 'Sir MV Layout',
    ],
  },
];

export function nameToSlug(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Full 76 localities database with specialized geotechnical, bylaw, and pricing data
const rawLocalities: Array<{
  name: string;
  zone: 'Central Core' | 'North Zone' | 'South Zone' | 'East Zone' | 'West Zone';
  zoneSlug: 'central' | 'north' | 'south' | 'east' | 'west';
  pincode: string;
  tagline: string;
  overview: string;
  bylawAuthority: string;
  farAndSetbacks: string;
  soilAndFoundation: string;
  waterAndBorewell: string;
  popularStyles: string[];
  avgCostPerSqFt: { essential: number; executive: number; luxury: number };
  keyLandmarks: string[];
}> = [
  // ── Central Core (16) ──
  {
    name: 'Lavelle Road',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560001',
    tagline: 'Ultra-Luxury Bespoke Residences & Heritage Mansions',
    overview: 'Lavelle Road represents the pinnacle of Bengaluru luxury living. Construction here commands premium architectural specifications, high-grade Italian marble finishes, basement parking engineering, and strict BBMP tree-preservation setback compliance.',
    bylawAuthority: 'BBMP Central Ward / Heritage Precinct Guidelines',
    farAndSetbacks: 'FAR 2.0 – 2.5 subject to 50ft+ road width. Minimum 2.5m rear and side setbacks. Strict basement excavation retaining wall mandates.',
    soilAndFoundation: 'Red gravelly clay over metamorphic granite rock strata. Safe Bearing Capacity (SBC) 220–250 kN/m². Combined raft or deep isolated footings with plinth tie beams.',
    waterAndBorewell: 'BWSSB Cauvery piped water connected. Borewells average 450–600 ft. Mandatory 5,000L rainwater harvesting percolation sump.',
    popularStyles: ['Neo-Classical Heritage', 'Contemporary Glass Villa', 'Modern European Penthouse'],
    avgCostPerSqFt: { essential: 2200, executive: 2800, luxury: 4200 },
    keyLandmarks: ['UB City', 'Cubbon Park', 'Bangalore Club'],
  },
  {
    name: 'Richmond Town',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560025',
    tagline: 'Colonial Elegance & Modern Turnkey Bungalow Re-Developments',
    overview: 'Richmond Town features tranquil tree-lined avenues with a rich heritage fabric. Home construction focuses on contemporary duplex conversions, courtyard architecture, and high acoustic insulation.',
    bylawAuthority: 'BBMP East Ward / Shanthalanagar Jurisdiction',
    farAndSetbacks: 'FAR 1.75 – 2.25. Setbacks 2.0m on sides. Front setback strictly aligned with historic road edge building lines.',
    soilAndFoundation: 'Dense red sandy loam. SBC 190–210 kN/m². Conventional isolated RCC footings with anti-termite chemical barrier grid.',
    waterAndBorewell: 'Reliable Cauvery water supply. Groundwater depth 500 ft. Dual piping for greywater recycling mandatory.',
    popularStyles: ['Colonial Revival', 'Courtyard Bungalow', 'Minimalist Concrete & Wood'],
    avgCostPerSqFt: { essential: 2100, executive: 2650, luxury: 3800 },
    keyLandmarks: ['Richmond Park', 'Hosur Road Junction', 'Sacred Heart Church'],
  },
  {
    name: 'MG Road',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560001',
    tagline: 'Commercial Mixed-Use & Prime CBD Residences',
    overview: 'As the commercial nerve center of Bengaluru, construction along and off MG Road specializes in boutique commercial complexes, luxury rooftop penthouses, and high-tech corporate office interiors.',
    bylawAuthority: 'BBMP Central Zone / BDA Commercial Corridor',
    farAndSetbacks: 'FAR up to 3.0 for commercial and mixed-use plots with wide frontage. Strict structural fire safety and handicap accessibility compliance.',
    soilAndFoundation: 'Hard weathered rock at shallow depth (6–10 ft). SBC 240 kN/m². Reinforced concrete shear walls and grade-beam foundations.',
    waterAndBorewell: 'BWSSB commercial metering. High-efficiency automated rainwater percolation recharge wells.',
    popularStyles: ['High-Tech Commercial Glass Curtain', 'Boutique Mixed-Use Suites', 'Industrial Chic'],
    avgCostPerSqFt: { essential: 2300, executive: 2950, luxury: 4400 },
    keyLandmarks: ['Trinity Metro Station', 'Anil Kumble Circle', 'Brigade Road Junction'],
  },
  {
    name: 'Cunningham Road',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560052',
    tagline: 'Prestigious Architectural Villas & Private Clinics',
    overview: 'Connecting Queen\'s Road to Chandrika Circle, Cunningham Road demands quiet luxury, sophisticated subterranean parking design, and bespoke acoustic facade engineering.',
    bylawAuthority: 'BBMP Central / Vasanth Nagar Ward',
    farAndSetbacks: 'FAR 2.0 with strict height caps due to proximity to the Governor\'s Residence / High Court corridor.',
    soilAndFoundation: 'Stable red sandy clay. SBC 210 kN/m². Deep isolated trapezoidal footings with plinth beam grids.',
    waterAndBorewell: 'Excellent Cauvery piped connection. Groundwater at 450 ft.',
    popularStyles: ['Art Deco Revival', 'Contemporary Luxury Duplex', 'Nordic Minimalist'],
    avgCostPerSqFt: { essential: 2250, executive: 2850, luxury: 4100 },
    keyLandmarks: ['Chandrika Hotel', 'Fatty Bao Lane', 'Sigma Central Mall'],
  },
  {
    name: 'Vasanth Nagar',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560052',
    tagline: 'High-Profile Residences & Boutique Commercial Spaces',
    overview: 'Adjacent to Palace Road and Cantonment, Vasanth Nagar requires elegant multi-tier homes with rooftop garden terraces, home elevators, and discreet security architecture.',
    bylawAuthority: 'BBMP Central / Vasanth Nagar Ward 93',
    farAndSetbacks: 'FAR 1.75 – 2.25. Setbacks 1.5m – 2.0m. Rainwater harvesting certificate required for plan sanction.',
    soilAndFoundation: 'Red loam with good drainage. SBC 195 kN/m². Standard RCC framed structure with Fe550D TMT steel reinforcement.',
    waterAndBorewell: 'BWSSB Cauvery network. Average borewell depth 500 ft.',
    popularStyles: ['Modern Tropical Luxury', 'Classical Chettinad-Infused Contemporary'],
    avgCostPerSqFt: { essential: 2150, executive: 2700, luxury: 3900 },
    keyLandmarks: ['Bangalore Palace Grounds', 'Mount Carmel College', 'Cantonment Railway Station'],
  },
  {
    name: 'Sadashivanagar',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560080',
    tagline: 'Billionaire Boulevard: Palace-View Luxury Mansions',
    overview: 'Home to industrial leaders, diplomats, and political figures. Construction projects here are expansive bespoke mansions with infinity rooftop pools, thermal double-glazed facades, and private 4-car basements.',
    bylawAuthority: 'BBMP North Zone / Ward 35 Aramane Nagar',
    farAndSetbacks: 'FAR 1.75. Wide setbacks (3.0m+) adhering to large parcel plot guidelines and canopy tree conservation.',
    soilAndFoundation: 'Rocky granite base under 8ft overburden. SBC 260 kN/m². Exceptional structural foundation stability with minimal settlement.',
    waterAndBorewell: 'Perennial Cauvery water connectivity. Mandatory 10,000L groundwater recharge well system.',
    popularStyles: ['Grand Neo-Classical Mansion', 'Tropical Zen Modern', 'Brutalist Concrete & Teak'],
    avgCostPerSqFt: { essential: 2400, executive: 3200, luxury: 4800 },
    keyLandmarks: ['Sankey Tank', 'Palace Orchards', 'CV Raman Road'],
  },
  {
    name: 'Malleshwaram',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560003',
    tagline: 'Heritage Roots with Contemporary Duplex Living',
    overview: 'One of Bengaluru\'s oldest planned suburbs. Modern builds focus on traditional Vaastu-compliant multi-generational family residences, courtyard homes, and space-maximized narrow-plot duplexes.',
    bylawAuthority: 'BBMP West / Malleshwaram Division Ward 45',
    farAndSetbacks: 'FAR 1.75. Strict street-width setback formulas for 30x40 and 40x60 plots.',
    soilAndFoundation: 'Dense red clayey loam. SBC 180–200 kN/m². Reinforced isolated footings with high-durability waterproof membrane.',
    waterAndBorewell: 'Comprehensive Cauvery network. Groundwater depth 550 ft.',
    popularStyles: ['Traditional South-Indian Courtyard', 'Modern Vaastu Duplex', 'Contemporary Brick & Stone'],
    avgCostPerSqFt: { essential: 1950, executive: 2450, luxury: 3400 },
    keyLandmarks: ['8th Cross Market', 'Kadu Malleshwara Temple', 'CTR Circle'],
  },
  {
    name: 'Frazer Town',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560005',
    tagline: 'Colonial Bungalow Rebirth & Luxury Low-Rise Living',
    overview: 'Frazer Town (Pulakeshinagar) demands tasteful preservation of Victorian streetscapes combined with cutting-edge smart home automation, open floor plans, and double-height living spaces.',
    bylawAuthority: 'BBMP East / Pulakeshinagar Ward 78',
    farAndSetbacks: 'FAR 1.75 – 2.0. Side setbacks 1.5m. Roof terrace solar installation mandates.',
    soilAndFoundation: 'Red sandy loam with excellent drainage. SBC 190 kN/m². Isolated pad footings with plinth tie beams.',
    waterAndBorewell: 'Cauvery line established. Rainwater harvesting tanks mandatory for Occupancy Certificate (OC).',
    popularStyles: ['Victorian Facade Modern Interior', 'Industrial Brick Lofts', 'Minimalist White Villa'],
    avgCostPerSqFt: { essential: 2050, executive: 2550, luxury: 3600 },
    keyLandmarks: ['Coles Park', 'Mosque Road', 'Pulakeshinagar Club'],
  },
  {
    name: 'Cox Town',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560005',
    tagline: 'Cantonment Heritage & Boutique Residential Enclaves',
    overview: 'Quiet residential cantonment neighborhood with mature trees. Builds here prioritize natural ventilation, terracotta louver facades, and luxury 3-story family residences.',
    bylawAuthority: 'BBMP East / Sarvagnanagar Division',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks for 40x60 and 50x80 plots.',
    soilAndFoundation: 'Stable red gravelly sand. SBC 195 kN/m². Conventional RCC column-beam framework.',
    waterAndBorewell: 'BWSSB Cauvery network active.',
    popularStyles: ['Modern Cantonment Villa', 'Contemporary Exposed Brick Home'],
    avgCostPerSqFt: { essential: 2000, executive: 2500, luxury: 3500 },
    keyLandmarks: ['ITC Infotech Park', 'Cox Town Market', 'Wheeler Road Extension'],
  },
  {
    name: 'Benson Town',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560046',
    tagline: 'Upscale Central Living & Designer Penthouse Duplexes',
    overview: 'Benson Town is a serene, leafy enclave favored by professionals. Turnkey projects feature rooftop entertainment decks, acoustic glass, and premium German modular kitchens.',
    bylawAuthority: 'BBMP East / Jayamahal Ward',
    farAndSetbacks: 'FAR 1.75 – 2.25 based on road clearance. Minimum 1.75m rear setbacks.',
    soilAndFoundation: 'Red loam over granite bedrock. SBC 200 kN/m². High-grade waterproofed foundation.',
    waterAndBorewell: 'Cauvery piped water. Borewells at 600 ft average.',
    popularStyles: ['Ultra-Modern Glass Duplex', 'Scandinavian Minimalist'],
    avgCostPerSqFt: { essential: 2100, executive: 2600, luxury: 3700 },
    keyLandmarks: ['Nandidurga Road', 'Benson Cross Road', 'Jayamahal Park'],
  },
  {
    name: 'Cooke Town',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560005',
    tagline: 'Artistic Boutique Residences & Heritage Conversions',
    overview: 'A tranquil cosmopolitan pocket with vibrant cafe culture. Construction focuses on sustainable architectural builds, terracotta tile finishes, and open-plan skylight courtyards.',
    bylawAuthority: 'BBMP East / Sarvagnanagar',
    farAndSetbacks: 'FAR 1.75. 1.5m side clearance. BBMP sanction approvals typically 3–4 weeks.',
    soilAndFoundation: 'Good bearing sandy red loam. SBC 195 kN/m².',
    waterAndBorewell: 'BWSSB Cauvery water. Dual flush plumbing setup.',
    popularStyles: ['Terracotta Contemporary', 'Urban Chic Courtyard Residence'],
    avgCostPerSqFt: { essential: 2050, executive: 2550, luxury: 3650 },
    keyLandmarks: ['Milton Park', 'Hutchins Road', 'ITC Green Centre'],
  },
  {
    name: 'Ulsoor',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560008',
    tagline: 'Lakeside Views & Central City Residences',
    overview: 'Bordering the historic Ulsoor Lake, construction projects emphasize lake-view balconies, damp-proof basement engineering, and modern high-specification turnkey execution.',
    bylawAuthority: 'BBMP East / Halasuru Ward 90',
    farAndSetbacks: 'FAR 1.75. Lake buffer zone regulations strictly respected (outside 30m buffer).',
    soilAndFoundation: 'Alluvial sandy clay near lake perimeter; rocky strata toward Kensington Road. SBC 170–190 kN/m². Specialized 3-coat waterproofing barrier on foundations.',
    waterAndBorewell: 'Perennial water table. High-grade waterproofing mandatory.',
    popularStyles: ['Lakeside Contemporary Villa', 'Modern Glass Penthouse'],
    avgCostPerSqFt: { essential: 2000, executive: 2500, luxury: 3600 },
    keyLandmarks: ['Ulsoor Lake', 'Kensington Road', 'Someshwara Temple'],
  },
  {
    name: 'Shanthi Nagar',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560027',
    tagline: 'High-Demand Central Corridor & Multi-Unit Homes',
    overview: 'Close to Lalbagh and Richmond Road, Shanthi Nagar is ideal for multi-unit rental duplexes, high-end private family villas, and commercial consultancies.',
    bylawAuthority: 'BBMP South / Ward 117 Shanthi Nagar',
    farAndSetbacks: 'FAR 1.75 – 2.25. Road widths 30–50 ft dictate maximum allowable G+3 height.',
    soilAndFoundation: 'Dense red soil. SBC 200 kN/m². Reliable isolated pad footings.',
    waterAndBorewell: 'BWSSB Cauvery line fully active.',
    popularStyles: ['Modern Multi-Story Duplex', 'Contemporary Stone-Clad Home'],
    avgCostPerSqFt: { essential: 1950, executive: 2450, luxury: 3450 },
    keyLandmarks: ['Shanthi Nagar Bus Station', 'Lalbagh Botanical Garden', 'Kanteerava Stadium'],
  },
  {
    name: 'Langford Town',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560025',
    tagline: 'Exclusive Elite Enclave with Stately Mansions',
    overview: 'Secluded luxury precinct featuring some of Bengaluru’s most private estates. Builds require premier acoustic insulation, bespoke Italian marble flooring, and smart automation systems.',
    bylawAuthority: 'BBMP East / Shanthalanagar',
    farAndSetbacks: 'FAR 1.75 – 2.0. Large front setbacks for landscaped driveways.',
    soilAndFoundation: 'Granite bedrock at 10–12 ft. SBC 220 kN/m².',
    waterAndBorewell: 'Dependable Cauvery water grid. Rainwater collection required.',
    popularStyles: ['Stately Classical Mansion', 'Modern Glass & Timber Villa'],
    avgCostPerSqFt: { essential: 2200, executive: 2800, luxury: 4100 },
    keyLandmarks: ['Langford Gardens', 'Baldwin Boys High School', 'Richmond Park'],
  },
  {
    name: 'Victoria Layout',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560047',
    tagline: 'Prestige Central Living Next to MG Road & CBD',
    overview: 'Tucked between Austin Town and Hosur Road, Victoria Layout offers central convenience with serene residential streets. Specializes in luxury 3-story townhomes and smart villas.',
    bylawAuthority: 'BBMP East / Ward 111',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks for 30x50 and 40x60 residential plots.',
    soilAndFoundation: 'Stable red sandy loam. SBC 195 kN/m².',
    waterAndBorewell: 'Active Cauvery water network.',
    popularStyles: ['Urban Townhome Duplex', 'Modern Contemporary Villa'],
    avgCostPerSqFt: { essential: 2050, executive: 2550, luxury: 3700 },
    keyLandmarks: ['Lifestyle Victoria Road', 'Commands Hospital', 'MG Road Metro'],
  },
  {
    name: 'Ashok Nagar',
    zone: 'Central Core',
    zoneSlug: 'central',
    pincode: '560025',
    tagline: 'Heart of Central Bengaluru Luxury & Commerce',
    overview: 'Ashok Nagar encompasses prime real estate directly adjacent to Brigade Road and Museum Road. Residential builds focus on ultra-luxury duplexes with custom imported fixtures and private elevators.',
    bylawAuthority: 'BBMP Central / Ashok Nagar Division',
    farAndSetbacks: 'FAR up to 2.5 on wide arterial roads. Strict seismic zone II structural compliance.',
    soilAndFoundation: 'Metamorphic granite rock base. SBC 230 kN/m².',
    waterAndBorewell: 'BWSSB Cauvery piped water connected.',
    popularStyles: ['Metropolitan Luxury Villa', 'Modern High-Rise Duplex Penthouse'],
    avgCostPerSqFt: { essential: 2250, executive: 2850, luxury: 4200 },
    keyLandmarks: ['Garuda Mall', 'Museum Road', 'St. Joseph\'s College'],
  },

  // ── North Zone (15) ──
  {
    name: 'Hebbal',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560024',
    tagline: 'Airport Gateway: Luxury Lakefront Villas & Tech High-Rises',
    overview: 'Hebbal is the premier gateway of North Bengaluru with rapid appreciation. Turnkey construction features lakefront luxury duplexes, seismic-resistant RCC frames, and advanced acoustic glazing against flyover noise.',
    bylawAuthority: 'BBMP North / BDA North Development Zone',
    farAndSetbacks: 'FAR 2.0 – 2.5 on Bellary Road arterial corridor. Standard 2.0m setbacks.',
    soilAndFoundation: 'Clayey silt near lake basin transitioning to hard red soil. SBC 180 kN/m². Raft foundations recommended for multi-story builds near water table.',
    waterAndBorewell: 'Good groundwater at 400 ft. Cauvery Stage V line expansion.',
    popularStyles: ['Modern High-Tech Villa', 'Contemporary Minimalist Duplex'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3300 },
    keyLandmarks: ['Hebbal Flyover', 'Hebbal Lake', 'Kirloskar Tech Park', 'Esteem Mall'],
  },
  {
    name: 'Yelahanka',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560064',
    tagline: 'Serene Plotted Communities & Sprawling Modern Villas',
    overview: 'With wide roads and clean air, Yelahanka is Bengaluru’s prime villa haven. Projects focus on 4BHK and 5BHK luxury independent homes, solar net-metering setups, and open landscape courtyards.',
    bylawAuthority: 'BBMP Yelahanka Zone / BDA Satellite Town',
    farAndSetbacks: 'FAR 1.75. Generous road widths allow smooth sanction approvals for G+3 residential plans.',
    soilAndFoundation: 'Hard gravelly red soil with high load-bearing capacity. SBC 210–230 kN/m². Economical isolated pad footings.',
    waterAndBorewell: 'Borewells average 600–750 ft. Rooftop rainwater harvesting essential.',
    popularStyles: ['Contemporary Sprawling Villa', 'Neo-Tropical Courtyard Home'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3100 },
    keyLandmarks: ['Yelahanka Air Force Station', 'Allalasandra Lake', 'BMSIT Campus'],
  },
  {
    name: 'Jakkur',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560064',
    tagline: 'Aerodrome Views & Sustainable Luxury Farmhouse Villas',
    overview: 'Renowned for Jakkur Aerodrome and Jakkur Lake, this area features sustainable biophilic architecture, exposed wirecut brickwork, and expansive eco-luxury homes.',
    bylawAuthority: 'BBMP North Zone / Byatarayanapura Ward 7',
    farAndSetbacks: 'FAR 1.75. Height regulations applicable near Jakkur Aerodrome flight funnel zone.',
    soilAndFoundation: 'Red sandy loam. SBC 195 kN/m². Good natural soil drainage.',
    waterAndBorewell: 'High water table near lake buffer. 5,000L recharge sump mandatory.',
    popularStyles: ['Biophilic Eco-Villa', 'Exposed Brick & Mangalore Tile Contemporary'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3250 },
    keyLandmarks: ['Jakkur Aerodrome', 'Jakkur Lake Bird Sanctuary', 'Agrahara Lake'],
  },
  {
    name: 'Sahakar Nagar',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560092',
    tagline: 'Pristine Planned Layout with Upscale Family Residences',
    overview: 'A premier residential layout established by telecom engineers. Known for uniform 40x60 and 50x80 plots, park-facing homes, and high-quality RCC multi-story family homes.',
    bylawAuthority: 'BBMP North / Byatarayanapura Ward 8',
    farAndSetbacks: 'FAR 1.75. Setbacks 1.5m – 2.0m strictly inspected by ward engineers.',
    soilAndFoundation: 'Firm red gravel. SBC 205 kN/m². Conventional RCC framed structures.',
    waterAndBorewell: 'Cauvery connection active. Borewell depth 500–650 ft.',
    popularStyles: ['Modern Multi-Story Duplex', 'Contemporary Italian-Tiled Villa'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3200 },
    keyLandmarks: ['Sahakar Nagar Main Road', 'Swathi Gardenia', 'BBMP Public Park'],
  },
  {
    name: 'Thanisandra',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560077',
    tagline: 'Tech Corridor Growth & Multi-Unit Rental Duplexes',
    overview: 'Booming residential corridor near Manyata Tech Park. High demand for G+3 multi-unit duplexes combining ground-floor family living with high-rental-yield upper floors.',
    bylawAuthority: 'BBMP North Zone / Thanisandra Ward 6',
    farAndSetbacks: 'FAR 1.75 – 2.25 on Thanisandra Main Road.',
    soilAndFoundation: 'Red soil with clay pockets. SBC 185 kN/m². Continuous plinth tie beams recommended.',
    waterAndBorewell: 'Borewells average 700 ft. Mandatory rainwater harvesting.',
    popularStyles: ['High-Yield Rental Duplex', 'Modern Minimalist Facade'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['Thanisandra Main Road', 'Elements Mall', 'Bhartiya City'],
  },
  {
    name: 'Hennur Road',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560043',
    tagline: 'Cosmopolitan Living & Gated Community Duplexes',
    overview: 'Vibrant corridor connecting Cantonment to airport road. Features international schools and gated residential communities. Ideal for modern 4BHK architectural villas.',
    bylawAuthority: 'BBMP East & BMRDA Corridor',
    farAndSetbacks: 'FAR 1.75. Road width 60ft+ on main road grants enhanced FAR for commercial.',
    soilAndFoundation: 'Red sandy gravel. SBC 200 kN/m².',
    waterAndBorewell: 'Groundwater 650 ft. Rainwater recharge pits mandatory.',
    popularStyles: ['European Contemporary Villa', 'Modern Glass & Concrete Home'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3050 },
    keyLandmarks: ['Hennur Flyover', 'Bio-Miracle Arena', 'Gubbi Cross'],
  },
  {
    name: 'Devanahalli',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '562110',
    tagline: 'Aerotropolis & Large-Plot Luxury Villas',
    overview: 'The epicentre of Bengaluru\'s infrastructure growth near Kempegowda International Airport. Large 60x80 and 80x100 plots allow sprawling resort-style villas with private pools.',
    bylawAuthority: 'BIAAPA (Bangalore International Airport Area Planning Authority)',
    farAndSetbacks: 'BIAAPA guidelines: FAR 1.5 – 1.75. Generous open green space requirements.',
    soilAndFoundation: 'Dense red rocky soil. SBC 230 kN/m². Highly stable foundation strata.',
    waterAndBorewell: 'Borewells 750–900 ft. Solar rooftop water heaters and rainwater sumps mandatory.',
    popularStyles: ['Resort-Style Sprawling Villa', 'Contemporary Farmhouse', 'Minimalist Mediterranean'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3100 },
    keyLandmarks: ['Kempegowda International Airport', 'Devanahalli Fort', 'KIADB Aerospace SEZ'],
  },
  {
    name: 'Manyata Tech Park',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560045',
    tagline: 'High-Yield Residential Duplexes for Tech Leaders',
    overview: 'Surrounding India’s largest operational tech park, builds here prioritize smart home automation, high-speed fibre conduits, soundproof windows, and rental executive suites.',
    bylawAuthority: 'BBMP North / Nagavara Ward',
    farAndSetbacks: 'FAR 1.75 – 2.0. Parking space minimum 1 car per 1000 sqft built-up area.',
    soilAndFoundation: 'Red clayey sand. SBC 190 kN/m².',
    waterAndBorewell: 'Borewell depth 600 ft. Cauvery water connection expanding.',
    popularStyles: ['Smart Modern Villa', 'Executive Rental Multiplex'],
    avgCostPerSqFt: { essential: 1750, executive: 2250, luxury: 3100 },
    keyLandmarks: ['Manyata Embassy Business Park', 'Nagavara Lake', 'Outer Ring Road Hebbal'],
  },
  {
    name: 'Vidyaranyapura',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560097',
    tagline: 'Spacious Multi-Generational Family Homes & Wide Roads',
    overview: 'Established residential locality popular among scientists and defense veterans. Strong preference for Vaastu-aligned duplexes with central skylights and garden setbacks.',
    bylawAuthority: 'BBMP Yelahanka Zone / Ward 9',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks for 30x40 and 40x60 sites.',
    soilAndFoundation: 'Red loam with good bearing capacity. SBC 195 kN/m².',
    waterAndBorewell: 'Cauvery connection active. Groundwater at 550 ft.',
    popularStyles: ['Vaastu-Compliant Modern Duplex', 'Traditional Teak & Concrete Villa'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['BEL Circle', 'Vidyaranyapura Main Bus Stand', 'NTI Layout'],
  },
  {
    name: 'RMV Extension',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560094',
    tagline: 'Prestigious Prime North Residential Enclave',
    overview: 'Raj Mahal Vilas Extension is North Bengaluru’s most elite address. Wide avenues, high-profile neighbors, and large plot sizes demand top-of-the-line architectural luxury and imported finishes.',
    bylawAuthority: 'BBMP North / Ward 34 Ganganagar',
    farAndSetbacks: 'FAR 1.75. Setbacks 2.5m+. Strict construction debris management rules.',
    soilAndFoundation: 'Rock foundation strata at 8ft. SBC 250 kN/m². Exceptional structural stability.',
    waterAndBorewell: 'Cauvery water connection active. 10,000L storage sump standard.',
    popularStyles: ['Grand Architectural Villa', 'Modern International Style', 'Zen Courtyard Residence'],
    avgCostPerSqFt: { essential: 2200, executive: 2800, luxury: 4000 },
    keyLandmarks: ['Sankey Tank North', 'Ramaiah Hospital', 'CPRI Road'],
  },
  {
    name: 'RT Nagar',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560032',
    tagline: 'Centrally Located Established North Hub',
    overview: 'Prime location connecting CBD with Hebbal. Builds focus on modern redevelopments of older 30x40 and 40x60 plots into sleek G+3 duplexes with stilt parking.',
    bylawAuthority: 'BBMP East / RT Nagar Ward',
    farAndSetbacks: 'FAR 1.75. Stilt parking floor mandatory for G+3 to avoid parking penalties.',
    soilAndFoundation: 'Red sandy loam. SBC 200 kN/m².',
    waterAndBorewell: 'Full BWSSB Cauvery network connectivity.',
    popularStyles: ['Modern Stilt+3 Duplex', 'Contemporary Urban Home'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3300 },
    keyLandmarks: ['RT Nagar Post Office', 'HMT Bhavan', 'Bellary Road Junction'],
  },
  {
    name: 'Sanjaynagar',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560094',
    tagline: 'Green Leafy Suburb with High Residential Quality',
    overview: 'Nestled between RMV and Bellary Road, Sanjaynagar attracts academics and senior executives. Custom homes feature rooftop terraces, solar PV setups, and warm wood-finish facades.',
    bylawAuthority: 'BBMP North / Ward 19',
    farAndSetbacks: 'FAR 1.75. Side setback minimum 1.5m.',
    soilAndFoundation: 'Red loam over granite. SBC 210 kN/m².',
    waterAndBorewell: 'Cauvery piped water available.',
    popularStyles: ['Warm Contemporary Villa', 'Modern Sustainable Duplex'],
    avgCostPerSqFt: { essential: 1900, executive: 2400, luxury: 3400 },
    keyLandmarks: ['Vaibhav Theatre Circle', 'ISRO Headquarters Link', 'Geddalahalli Park'],
  },
  {
    name: 'Bellary Road',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560092',
    tagline: 'Premier North Highway Arterial Corridor',
    overview: 'The high-speed expressway connecting central Bengaluru to the airport. High demand for commercial showrooms, boutique headquarters, and ultra-luxury gated duplexes set back from the highway.',
    bylawAuthority: 'BBMP / BDA Corridor Planning',
    farAndSetbacks: 'FAR up to 2.5 on wide service roads. Strict service-road access and parking norms.',
    soilAndFoundation: 'Hard gravelly clay. SBC 220 kN/m².',
    waterAndBorewell: 'BWSSB water lines expanding.',
    popularStyles: ['Commercial Glass Monolith', 'Luxury Highway Frontage Duplex'],
    avgCostPerSqFt: { essential: 1900, executive: 2450, luxury: 3500 },
    keyLandmarks: ['Columbia Asia Hebbal', 'Aster CMI Hospital', 'GKVK University Campus'],
  },
  {
    name: 'Kogilu',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '560064',
    tagline: 'Rapidly Rising Residential Layout near Yelahanka',
    overview: 'Affordable high-growth corridor between Yelahanka and airport expressway. Ideal for first-time home builders seeking spacious 30x40 and 40x60 duplexes with modern amenities.',
    bylawAuthority: 'BBMP Yelahanka Division',
    farAndSetbacks: 'FAR 1.75. Straightforward municipal plan approvals.',
    soilAndFoundation: 'Red sandy soil. SBC 190 kN/m².',
    waterAndBorewell: 'Borewells average 700 ft.',
    popularStyles: ['Budget Contemporary Duplex', 'Modern 3BHK Family Villa'],
    avgCostPerSqFt: { essential: 1650, executive: 2100, luxury: 2900 },
    keyLandmarks: ['Kogilu Cross', 'Prakriya Green Wisdom School', 'Yelahanka Bypass'],
  },
  {
    name: 'Doddaballapur Road',
    zone: 'North Zone',
    zoneSlug: 'north',
    pincode: '561203',
    tagline: 'Institutional Corridor & Expansive Eco-Villas',
    overview: 'Hub of premier universities and industrial developments. Construction trends here favor large farm plots, eco-conscious residences, solar-powered off-grid living, and weekend villas.',
    bylawAuthority: 'BIAAPA & BMRDA Planning Jurisdiction',
    farAndSetbacks: 'FAR 1.5. Large open space ratios.',
    soilAndFoundation: 'Hard red soil with granite boulders. SBC 220 kN/m².',
    waterAndBorewell: 'Borewell water reliable at 750 ft. Large rainwater sumps required.',
    popularStyles: ['Eco-Farmhouse Villa', 'Rammed Earth & Exposed Concrete Modern'],
    avgCostPerSqFt: { essential: 1650, executive: 2100, luxury: 2950 },
    keyLandmarks: ['Gitman University', 'BMSIT Yelahanka', 'Doddaballapur Industrial Area'],
  },

  // ── South Zone (15) ──
  {
    name: 'Koramangala',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560034',
    tagline: 'Startup Capital: Tech Billionaire Mansions & Luxury Duplexes',
    overview: 'Koramangala (Blocks 3, 4, and 5 in particular) boasts some of India\'s most valued residential land. Turnkey builds require world-class engineering, double-height living rooms, Italian marble flooring, and subterranean home theatres.',
    bylawAuthority: 'BBMP South / Ward 151 Koramangala',
    farAndSetbacks: 'FAR 1.75 – 2.25. Road widths 40–80 ft allow luxury villa heights. Side setbacks 2.0m minimum.',
    soilAndFoundation: 'Dense red clayey loam over granite rock. SBC 210 kN/m². Isolated pad footings with heavy plinth tie-beam reinforcements.',
    waterAndBorewell: 'Reliable Cauvery water supply. Mandatory 5,000L rainwater harvesting recharge pit.',
    popularStyles: ['Billionaire Contemporary Villa', 'Modern Glass & Teak Mansion', 'Minimalist Industrial Penthouse'],
    avgCostPerSqFt: { essential: 2200, executive: 2850, luxury: 4200 },
    keyLandmarks: ['Koramangala 3rd Block Billionaire Street', 'Forum Mall', 'Wipro Park', 'Sony World Signal'],
  },
  {
    name: 'HSR Layout',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560102',
    tagline: 'Modern Silicon Suburb: G+3 Tech Founder Homes',
    overview: 'Planned across 7 sectors with wide grid roads. High demand for G+3 and G+4 independent multi-level residences featuring stilt parking, private terrace gardens, and dedicated home-office pods.',
    bylawAuthority: 'BBMP South / Bommanahalli Zone Ward 174',
    farAndSetbacks: 'FAR 1.75 – 2.0. Strict BBMP setback guidelines: 1.5m side and 2.0m rear on standard 30x40 and 40x60 plots.',
    soilAndFoundation: 'Red gravelly clay. SBC 195–215 kN/m². Excellent structural stability with conventional RCC column-beam framework.',
    waterAndBorewell: 'Active Cauvery water network. Groundwater at 600 ft.',
    popularStyles: ['Modern Multi-Story Duplex', 'Minimalist Tech Villa', 'Contemporary Exposed Brickwork'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3350 },
    keyLandmarks: ['HSR Sector 1 to 7', 'Agara Lake', '27th Main Food Street'],
  },
  {
    name: 'Jayanagar',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560011',
    tagline: 'Historic Planned Grandeur & Vaastu Family Estates',
    overview: 'Regarded as one of Asia\'s best-planned residential layouts. Custom builds require meticulous adherence to traditional Vaastu Shastra, multi-car parking setups, and timeless architectural facades.',
    bylawAuthority: 'BBMP South / Jayanagar Division',
    farAndSetbacks: 'FAR 1.75. Wide tree-lined avenues allow seamless construction material staging and transport.',
    soilAndFoundation: 'Deep red loam over granite bedrock. SBC 200–220 kN/m². Reliable isolated footings.',
    waterAndBorewell: 'Comprehensive BWSSB Cauvery network.',
    popularStyles: ['Grand Vaastu Contemporary', 'Traditional Courtyard Mansion', 'Modern Stone-Clad Villa'],
    avgCostPerSqFt: { essential: 2000, executive: 2600, luxury: 3700 },
    keyLandmarks: ['Jayanagar 4th Block Complex', 'Madhavan Park', 'South End Circle'],
  },
  {
    name: 'JP Nagar',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560078',
    tagline: 'Cultural Hub: Designer Duplexes & Artist Residences',
    overview: 'Spanning phases 1 to 9, JP Nagar is a vibrant cultural enclave. Projects range from artistic 3BHK courtyard duplexes in Phase 1-3 to spacious modern gated villas in Phases 7-9.',
    bylawAuthority: 'BBMP South / JP Nagar Ward',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks for 40x60 plots.',
    soilAndFoundation: 'Red sandy clay with granite outcrop in southern phases. SBC 200 kN/m².',
    waterAndBorewell: 'Cauvery connection in Phases 1–6. Borewells average 650 ft.',
    popularStyles: ['Artistic Contemporary Duplex', 'Modern Minimalist Glass Home'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3300 },
    keyLandmarks: ['Ranga Shankara Theatre', 'Sarakki Lake', 'Central Mall JP Nagar'],
  },
  {
    name: 'BTM Layout',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560068',
    tagline: 'High-Density Rental Yield & Modern Multi-Unit Builds',
    overview: 'Positioned between Bannerghatta Road and Hosur Road. Prime territory for high-density G+3 and G+4 apartment-style duplexes engineered for maximum rental return on investment.',
    bylawAuthority: 'BBMP South / BTM Layout Ward 176',
    farAndSetbacks: 'FAR 1.75 – 2.0. Stilt parking floor mandatory for rental floor compliance.',
    soilAndFoundation: 'Red loam. SBC 190 kN/m².',
    waterAndBorewell: 'Cauvery piped water available. Rainwater harvesting tanks mandatory.',
    popularStyles: ['High-Yield Rental Multiplex', 'Contemporary Compact Duplex'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3000 },
    keyLandmarks: ['Madiwala Lake', 'Udupi Garden Signal', 'Silk Board Junction'],
  },
  {
    name: 'Bannerghatta Road',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560076',
    tagline: 'South Arterial Highway & Hill-Slope Gated Villas',
    overview: 'Connecting Dairy Circle to Jigani, this arterial corridor features rolling terrain. Builds demand stepped foundation engineering, retaining walls, and panoramic terrace designs.',
    bylawAuthority: 'BBMP South & BDA Southern Planning Zone',
    farAndSetbacks: 'FAR 1.75 – 2.25 based on road frontage.',
    soilAndFoundation: 'Granite bedrock near surface in upper stretches. SBC 230 kN/m². Exceptional structural foundation stability.',
    waterAndBorewell: 'Borewells average 650–800 ft. Water softening filtration systems recommended.',
    popularStyles: ['Terrace Hillside Villa', 'Modern Tropical Duplex'],
    avgCostPerSqFt: { essential: 1750, executive: 2250, luxury: 3150 },
    keyLandmarks: ['IIM Bangalore', 'Fortis Hospital', 'Vega City Mall', 'Bannerghatta National Park'],
  },
  {
    name: 'Electronic City',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560100',
    tagline: 'Tech Hub Living: Sustainable Smart Villas & Duplexes',
    overview: 'India’s pioneer electronics industrial park (Phases 1 & 2). Builds emphasize high-speed tech infrastructure, EV charging stations, solar net metering, and clean minimalist architecture.',
    bylawAuthority: 'ELCITA (Phase 1) & BBMP / BMRDA (Phase 2)',
    farAndSetbacks: 'FAR 1.75. ELCITA operates streamlined, prompt plan sanctions.',
    soilAndFoundation: 'Hard red soil with gravel. SBC 210 kN/m².',
    waterAndBorewell: 'Borewells 700–850 ft. Mandatory groundwater recharge percolation pits.',
    popularStyles: ['Smart Sustainable Villa', 'Modern Tech-Enabled Duplex'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3000 },
    keyLandmarks: ['Infosys Campus', 'Wipro Electronic City', 'Elevated Tollway Entrance'],
  },
  {
    name: 'Kanakapura Road',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560062',
    tagline: 'Green Corridor: Resort-Style Plotted Villas & Duplexes',
    overview: 'The green lung of South Bengaluru. Metro connectivity has spurred demand for spacious 4BHK and 5BHK luxury villas with private gardens, central courtyards, and rainwater recycling.',
    bylawAuthority: 'BBMP South & BDA Anjanapura Zone',
    farAndSetbacks: 'FAR 1.75. Generous plot dimensions facilitate low ground coverage and high open gardens.',
    soilAndFoundation: 'Rocky granite stratum at 6–8 ft. SBC 240 kN/m². Zero settlement risk.',
    waterAndBorewell: 'Good groundwater table at 550–700 ft.',
    popularStyles: ['Eco-Resort Villa', 'Contemporary Vaastu Duplex', 'Modern Stone & Teak Home'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3100 },
    keyLandmarks: ['Art of Living Ashram', 'Metro Green Line Terminal', 'Forum South Bengaluru Mall'],
  },
  {
    name: 'Padmanabhanagar',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560070',
    tagline: 'Peaceful South Haven: Traditional Multi-Level Family Homes',
    overview: 'Established residential locality close to Banashankari. Ideal for multi-generational families building spacious independent homes with traditional puja rooms, central halls, and rental penthouses.',
    bylawAuthority: 'BBMP South / Ward 182',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks.',
    soilAndFoundation: 'Red loam over rock. SBC 205 kN/m².',
    waterAndBorewell: 'Cauvery connection active.',
    popularStyles: ['Traditional South Indian Modern', 'Classic Brick & Granite Villa'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3200 },
    keyLandmarks: ['Deve Gowda Petrol Bunk Circle', 'Carmel School', 'DG Hospital'],
  },
  {
    name: 'Banashankari',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560085',
    tagline: 'Bengaluru’s Largest Suburb: Diverse Architectural Duplexes',
    overview: 'Stretching across 6 stages. From heritage-infused 40x60 homes in Stage 2 to contemporary 50x80 designer villas in Stage 6, turnkey construction covers the entire spectrum of residential excellence.',
    bylawAuthority: 'BBMP South / BDA Banashankari',
    farAndSetbacks: 'FAR 1.75. Road widths 30–60 ft dictate permissible elevations.',
    soilAndFoundation: 'Rocky granite base in stages 3 and 6. SBC 220 kN/m².',
    waterAndBorewell: 'Cauvery water connection active across Stages 1–3, expanding in 5–6.',
    popularStyles: ['Contemporary Vaastu Home', 'Modern Multi-Story Duplex'],
    avgCostPerSqFt: { essential: 1750, executive: 2250, luxury: 3150 },
    keyLandmarks: ['Banashankari Amma Temple', 'BDA Complex BSK 2nd Stage', 'PES University'],
  },
  {
    name: 'Harlur Road',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560102',
    tagline: 'Tech Commuter Corridor: Premium Modern Duplexes',
    overview: 'Connecting Sarjapur Road to HSR Layout. Favored by tech management professionals. Builds feature open floor plans, double-height atriums, and acoustic isolation.',
    bylawAuthority: 'BBMP Mahadevapura / Bommanahalli Boundary',
    farAndSetbacks: 'FAR 1.75. Setbacks 1.5m on sides.',
    soilAndFoundation: 'Red sandy clay. SBC 190 kN/m².',
    waterAndBorewell: 'Borewells average 700 ft. Water filtration plant integration standard.',
    popularStyles: ['Modern Minimalist Duplex', 'Nordic Light-Filled Home'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3200 },
    keyLandmarks: ['Harlur Lake', 'Vibgyor High School', 'Reliaable Lakedew Layout'],
  },
  {
    name: 'Kasavanahalli',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560035',
    tagline: 'Lakeside Enclave: Tech Executive Villas & Duplexes',
    overview: 'Parallel to Sarjapur Road with scenic lake surroundings. Projects emphasize private garden balconies, waterproofed basements, and smart energy-saving lighting systems.',
    bylawAuthority: 'BBMP Mahadevapura / Ward 150',
    farAndSetbacks: 'FAR 1.75. Lake buffer norms (30m) strictly adhered to.',
    soilAndFoundation: 'Clayey loam near lake. SBC 180 kN/m². Raft footing or deep isolated footings.',
    waterAndBorewell: 'Good groundwater table. Dual piping setup required.',
    popularStyles: ['Lakeside Contemporary Home', 'Modern Urban Duplex'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3100 },
    keyLandmarks: ['Kasavanahalli Lake', 'Amrita Vishwa Vidyapeetham', 'Central Jail Road'],
  },
  {
    name: 'Uttarahalli',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560061',
    tagline: 'Scenic Hillside Suburb: Spacious Family Duplexes',
    overview: 'Connecting Banashankari to Kengeri. Rolling geography allows stepped garden villas, rooftop gazebos, and cost-effective turnkey independent homes.',
    bylawAuthority: 'BBMP South Zone / Ward 184',
    farAndSetbacks: 'FAR 1.75. Straightforward plan approvals.',
    soilAndFoundation: 'Red soil over granite bedrock. SBC 210 kN/m².',
    waterAndBorewell: 'Borewell depth 650 ft.',
    popularStyles: ['Modern Hillside Home', 'Traditional Duplex'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['Uttarahalli Lake', 'Dr. Vishnuvardhan Memorial', 'Subramanyapura Police Station'],
  },
  {
    name: 'Begur',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560068',
    tagline: 'Heritage Roots & Fast-Growing Tech Suburb',
    overview: 'Historic lake town turned thriving residential hub off Hosur Road. Projects range from compact 30x40 rental homes to spacious 4BHK gated villas.',
    bylawAuthority: 'BBMP South / Bommanahalli Zone',
    farAndSetbacks: 'FAR 1.75. Standard BBMP bylaws.',
    soilAndFoundation: 'Red clayey loam. SBC 190 kN/m².',
    waterAndBorewell: 'Groundwater at 650 ft.',
    popularStyles: ['Budget Contemporary Duplex', 'Modern 4BHK Family Home'],
    avgCostPerSqFt: { essential: 1650, executive: 2100, luxury: 2900 },
    keyLandmarks: ['Begur Fort Lake', 'Panchalingeshwara Temple', 'Hosur Road Link'],
  },
  {
    name: 'Gottigere',
    zone: 'South Zone',
    zoneSlug: 'south',
    pincode: '560083',
    tagline: 'Bannerghatta Metro Corridor: Nature-Inspired Villas',
    overview: 'Positioned on the upcoming Metro corridor on Bannerghatta Road. Strong demand for nature-integrated villas with skylights, vertical gardens, and solar power generation.',
    bylawAuthority: 'BBMP South / Bommanahalli Ward 194',
    farAndSetbacks: 'FAR 1.75. Metro corridor influence zone rules.',
    soilAndFoundation: 'Red gravelly clay over rock. SBC 215 kN/m².',
    waterAndBorewell: 'Borewells average 700 ft.',
    popularStyles: ['Eco-Living Villa', 'Modern Multi-Story Duplex'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3000 },
    keyLandmarks: ['Gottigere Lake', 'Nice Ring Road Junction', 'Royal Meenakshi Mall'],
  },

  // ── East Zone (15) ──
  {
    name: 'Indiranagar',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560038',
    tagline: 'Cosmopolitan Crown: High-Fashion Mansions & Commercial Boutiques',
    overview: 'Indiranagar is Bengaluru\'s premier lifestyle capital. 100ft Road and 12th Main demand striking architectural landmarks, cantilevered balconies, designer boutique facades, and ultra-luxury residential penthouses.',
    bylawAuthority: 'BBMP East / CV Raman Nagar Division',
    farAndSetbacks: 'FAR 1.75 – 2.5 depending on road width (40ft vs 100ft). Side setbacks 2.0m minimum.',
    soilAndFoundation: 'Stable red sandy clay over granite. SBC 210 kN/m². High load-bearing capacity suitable for cantilevered architectural designs.',
    waterAndBorewell: 'Full BWSSB Cauvery supply. Borewells average 500 ft.',
    popularStyles: ['Ultra-Modern Cantilevered Villa', 'Industrial Chic Boutique', 'Scandinavian Minimalism'],
    avgCostPerSqFt: { essential: 2200, executive: 2800, luxury: 4200 },
    keyLandmarks: ['100 Feet Road', '12th Main Food Boulevard', 'Indiranagar Club', 'Defence Colony'],
  },
  {
    name: 'Whitefield',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560066',
    tagline: 'Silicon Heartland: Expansive Tech Villas & Luxury Duplexes',
    overview: 'The historic Anglo-Indian settlement turned global IT powerhouse. Turnkey construction features sprawling 4BHK and 5BHK luxury villas, gated community duplexes, soundproof home offices, and private swimming pools.',
    bylawAuthority: 'BBMP Mahadevapura Zone / BDA East',
    farAndSetbacks: 'FAR 1.75 – 2.0. Generous plot sizes allow spacious multi-car stilt parking and private perimeter gardens.',
    soilAndFoundation: 'Hard gravelly red soil with high bearing capacity. SBC 200–220 kN/m². Isolated trapezoidal footings with plinth tie-beam grid.',
    waterAndBorewell: 'Borewells average 750–900 ft. Water filtration systems and dual piping standard.',
    popularStyles: ['Modern Silicon Villa', 'Contemporary Anglo-Indian Revival', 'Minimalist Glass Duplex'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3400 },
    keyLandmarks: ['ITPB (International Tech Park)', 'Nexus Shantiniketan', 'EPIP Zone', 'Hope Farm Junction'],
  },
  {
    name: 'Sarjapur Road',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560035',
    tagline: 'Villa Haven: Gated Community Architecture & Green Homes',
    overview: 'The fastest-growing villa corridor in Bengaluru. High demand for custom-built 4BHK villas with solar net metering, rainwater harvesting systems, double-height living rooms, and private backyards.',
    bylawAuthority: 'BBMP & BMRDA Corridor Authority',
    farAndSetbacks: 'FAR 1.75. Wide interior layout roads streamline heavy construction vehicle access.',
    soilAndFoundation: 'Red loam with sandy gravel. SBC 190–210 kN/m².',
    waterAndBorewell: 'Borewells 700–850 ft. Large 5,000L to 10,000L recharge sumps mandatory.',
    popularStyles: ['Contemporary Gated Villa', 'Biophilic Green Home', 'Modern Multi-Gen Duplex'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3300 },
    keyLandmarks: ['Wipro Corporate Office', 'Carmelaram Railway Station', 'Decathlon Sarjapur'],
  },
  {
    name: 'Bellandur',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560103',
    tagline: 'ORR Tech Gateway: High-Specification Duplexes & Rental Suites',
    overview: 'Positioned along the Outer Ring Road tech corridor. Builds demand advanced 3-layer foundation waterproofing, acoustic double glazing, and multi-unit configurations for high rental returns.',
    bylawAuthority: 'BBMP Mahadevapura / Ward 150',
    farAndSetbacks: 'FAR 1.75 – 2.25 on main ORR feeder roads.',
    soilAndFoundation: 'Clayey silt near lake catchment. SBC 170–190 kN/m². Raft foundation or deep column footings with continuous plinth beams.',
    waterAndBorewell: 'High water table. High-grade crystalline waterproofing mandatory for all sub-grade structures.',
    popularStyles: ['High-Yield Modern Duplex', 'Tech Executive Villa'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3250 },
    keyLandmarks: ['Ecospace Business Park', 'EcoWorld Tech Park', 'Central Mall Bellandur'],
  },
  {
    name: 'Marathahalli',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560037',
    tagline: 'Central East Hub: Multi-Tier Rental & Commercial Builds',
    overview: 'Major transit and commercial intersection. Turnkey projects focus on G+3 and G+4 multi-family rental buildings, commercial showrooms, and modern compact duplexes.',
    bylawAuthority: 'BBMP Mahadevapura / Ward 85',
    farAndSetbacks: 'FAR 1.75 – 2.0. Parking space optimization critical.',
    soilAndFoundation: 'Red sandy loam. SBC 195 kN/m².',
    waterAndBorewell: 'Groundwater at 650 ft. Cauvery water line active in select wards.',
    popularStyles: ['Multi-Unit Rental Complex', 'Commercial Mixed-Use Building'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3050 },
    keyLandmarks: ['Marathahalli Bridge', 'Kalamandir Junction', 'Innovative Multiplex'],
  },
  {
    name: 'Varthur',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560087',
    tagline: 'Lake Suburb: Rapidly Evolving Plotted Villa Communities',
    overview: 'Connecting Whitefield to Sarjapur. High growth in gated plotted layouts where families build spacious independent duplex homes with generous gardens and modern architecture.',
    bylawAuthority: 'BBMP Mahadevapura Zone / Varthur Ward',
    farAndSetbacks: 'FAR 1.75. Lake buffer restrictions applicable within designated zones.',
    soilAndFoundation: 'Clayey loam transitioning to hard gravel. SBC 185 kN/m².',
    waterAndBorewell: 'Borewells average 700 ft.',
    popularStyles: ['Spacious 4BHK Villa', 'Contemporary Lake-Adjacent Home'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3000 },
    keyLandmarks: ['Varthur Lake', 'Varthur Police Station Circle', 'Gunjur Main Road'],
  },
  {
    name: 'CV Raman Nagar',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560093',
    tagline: 'Defense & Tech Elite: Tree-Covered Serene Mansions',
    overview: 'Adjacent to DRDO and Bagmane Tech Park. Highly organized residential enclave with wide avenues, mature canopy trees, and high-specification private family duplexes.',
    bylawAuthority: 'BBMP East / CV Raman Nagar Ward 83',
    farAndSetbacks: 'FAR 1.75. Strict BBMP setback inspection and tree conservation compliance.',
    soilAndFoundation: 'Hard red soil over granite. SBC 215 kN/m².',
    waterAndBorewell: 'BWSSB Cauvery network fully established.',
    popularStyles: ['Serene Contemporary Villa', 'Modern Architectural Duplex'],
    avgCostPerSqFt: { essential: 1950, executive: 2450, luxury: 3500 },
    keyLandmarks: ['Bagmane Tech Park', 'DRDO Township', 'BEML Hospital'],
  },
  {
    name: 'Mahadevapura',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560048',
    tagline: 'Industrial Transformation: Smart Homes & Rental Assets',
    overview: 'The administrative heart of East Bengaluru tech operations. High demand for modern G+3 residences with commercial retail on the ground floor and premium rental duplexes above.',
    bylawAuthority: 'BBMP Mahadevapura Zone Headquarters',
    farAndSetbacks: 'FAR 1.75 – 2.25 on major link roads.',
    soilAndFoundation: 'Red gravelly clay. SBC 195 kN/m².',
    waterAndBorewell: 'Borewells 700 ft. Rainwater recharge mandated.',
    popularStyles: ['Mixed-Use Commercial & Residential', 'Modern Compact Villa'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3100 },
    keyLandmarks: ['Phoenix Marketcity', 'VR Bengaluru', 'Mahadevapura Metro Station'],
  },
  {
    name: 'KR Puram',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560036',
    tagline: 'Old Madras Road Hub: Budget & Mid-Premium Duplexes',
    overview: 'Key transit corridor connecting Bengaluru to Chennai highway. Popular for affordable 30x40 and 40x60 independent homes, multi-story rental buildings, and commercial offices.',
    bylawAuthority: 'BBMP East / KR Puram Ward',
    farAndSetbacks: 'FAR 1.75. Road widths dictate permissible height limits.',
    soilAndFoundation: 'Red soil with rock outcroppings. SBC 200 kN/m².',
    waterAndBorewell: 'Cauvery connection expanding. Borewell depth 650 ft.',
    popularStyles: ['Practical Multi-Story Duplex', 'Modern Budget 3BHK Home'],
    avgCostPerSqFt: { essential: 1650, executive: 2100, luxury: 2900 },
    keyLandmarks: ['KR Puram Hanging Bridge', 'KR Puram Railway Station', 'Lake Garden'],
  },
  {
    name: 'Brookefield',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560037',
    tagline: 'Established Tech Enclave: Upscale Gated Duplexes',
    overview: 'Flanked by IT companies and international hospitals. Favored by senior tech executives. Builds feature private elevators, rooftop solar plants, and double-height glass atriums.',
    bylawAuthority: 'BBMP Mahadevapura / Ward 84',
    farAndSetbacks: 'FAR 1.75. Setbacks 1.5m – 2.0m.',
    soilAndFoundation: 'Hard red soil. SBC 205 kN/m².',
    waterAndBorewell: 'Borewells 700 ft. Water filtration systems required.',
    popularStyles: ['Upscale Contemporary Villa', 'Modern Glass Duplex'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3350 },
    keyLandmarks: ['AECS Layout', 'Kundalahalli Gate', 'Vydehi Hospital'],
  },
  {
    name: 'Hoodi',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560048',
    tagline: 'Metro-Connected Growth: High-Rise Adjacent Duplexes',
    overview: 'Adjacent to Whitefield with dedicated metro station. Excellent territory for smart modern duplexes with compact footprints and smart home automated controls.',
    bylawAuthority: 'BBMP Mahadevapura / Hoodi Ward',
    farAndSetbacks: 'FAR 1.75. Simple municipal sanction processes.',
    soilAndFoundation: 'Red sandy loam. SBC 195 kN/m².',
    waterAndBorewell: 'Groundwater at 750 ft.',
    popularStyles: ['Compact Modern Duplex', 'Smart Contemporary Home'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3100 },
    keyLandmarks: ['Hoodi Metro Station', 'Manipal Hospital Whitefield', 'Zuri Whitefield'],
  },
  {
    name: 'Kadugodi',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560067',
    tagline: 'Purple Line Metro Terminal: High-Potential Villa Suburb',
    overview: 'The eastern terminus of Namma Metro. Rapidly transforming with new plotted communities and luxury gated developments. Ideal for 4BHK independent homes.',
    bylawAuthority: 'BBMP Mahadevapura Zone',
    farAndSetbacks: 'FAR 1.75. Wide new layout roads allow easy material delivery.',
    soilAndFoundation: 'Dense red soil. SBC 200 kN/m².',
    waterAndBorewell: 'Borewells 800 ft. Rainwater collection sump mandatory.',
    popularStyles: ['Modern Gated Community Home', 'Contemporary 4BHK Duplex'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3000 },
    keyLandmarks: ['Whitefield (Kadugodi) Metro Station', 'Kadugodi Tree Park', 'Hope Farm Link'],
  },
  {
    name: 'Domlur',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560071',
    tagline: 'Prime Central-East Gateway: High-Value Residences & Tech HQs',
    overview: 'Bordering Indiranagar and Embassy Golf Links (EGL). High-value land parcel where construction focuses on luxury boutique residences, commercial offices, and rooftop entertainment decks.',
    bylawAuthority: 'BBMP East / Ward 112 Domlur',
    farAndSetbacks: 'FAR 1.75 – 2.25. Proximity to airport runway dictates height limits.',
    soilAndFoundation: 'Stable red sandy clay. SBC 205 kN/m².',
    waterAndBorewell: 'BWSSB Cauvery water active.',
    popularStyles: ['Luxury Urban Villa', 'Commercial Boutique Headquarter'],
    avgCostPerSqFt: { essential: 2100, executive: 2650, luxury: 3800 },
    keyLandmarks: ['Embassy Golf Links (EGL)', 'Domlur Flyover', 'Old Airport Road Junction'],
  },
  {
    name: 'Panathur',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '560103',
    tagline: 'ORR Tech Corridor Link: Modern Multi-Storey Homes',
    overview: 'Connecting ORR to Varthur. Rapid residential growth driven by IT workforce. Builds focus on efficient floor layouts, acoustic insulation, and multi-unit rental duplexes.',
    bylawAuthority: 'BBMP Mahadevapura',
    farAndSetbacks: 'FAR 1.75. Standard BBMP bylaws.',
    soilAndFoundation: 'Clayey loam. SBC 180 kN/m².',
    waterAndBorewell: 'Borewells 700 ft. High water table requires 2-layer foundation waterproofing.',
    popularStyles: ['Modern Rental Duplex', 'Contemporary Compact Home'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['Panathur Lake', 'Cessna Business Park Backgate', 'Kadubeesanahalli Signal'],
  },
  {
    name: 'Budigere Cross',
    zone: 'East Zone',
    zoneSlug: 'east',
    pincode: '562129',
    tagline: 'Airport-Tech Mega Corridor: Sprawling Luxury Villas',
    overview: 'The next major growth frontier connecting Whitefield to the International Airport. Wide multi-lane roads, large plot dimensions, and premier luxury township villas.',
    bylawAuthority: 'BMRDA & BIAAPA Planning Authorities',
    farAndSetbacks: 'FAR 1.5 – 1.75. Generous open green space allowances.',
    soilAndFoundation: 'Hard red soil with high SBC (220 kN/m²). Highly stable foundation ground.',
    waterAndBorewell: 'Borewells 750–900 ft. Solar water heating and rainwater sumps mandatory.',
    popularStyles: ['Modern Sprawling Villa', 'Contemporary Ranch-Style Home'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3050 },
    keyLandmarks: ['Budigere Cross Junction', 'Old Madras Road Expressway', 'Prestige City East'],
  },

  // ── West Zone (15) ──
  {
    name: 'Rajajinagar',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560010',
    tagline: 'West Bengaluru Royalty: Grand Family Mansions & Multi-Storey Duplexes',
    overview: 'Rajajinagar (Blocks 1 to 6) is the crown jewel of West Bengaluru. Builds require strong adherence to Vaastu Shastra, opulent teakwood interior joinery, and multi-car stilt parking for multi-generational living.',
    bylawAuthority: 'BBMP West / Rajajinagar Division',
    farAndSetbacks: 'FAR 1.75 – 2.0. Stilt parking floor recommended for G+3 residential plans.',
    soilAndFoundation: 'Granite bedrock at 6–8 ft depth under dense red soil. SBC 220–240 kN/m². Highly stable foundation base.',
    waterAndBorewell: 'Full BWSSB Cauvery water network connectivity.',
    popularStyles: ['Grand Traditional Vaastu Mansion', 'Contemporary Granite & Teak Villa', 'Modern Multi-Gen Duplex'],
    avgCostPerSqFt: { essential: 1950, executive: 2500, luxury: 3600 },
    keyLandmarks: ['World Trade Center (WTC)', 'Orion Mall', 'ISKCON Temple', 'Rajajinagar 1st Block'],
  },
  {
    name: 'Basavanagudi',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560004',
    tagline: 'Cultural Heritage Capital: Stately Courtyard Mansions',
    overview: 'One of the oldest planned areas of Bengaluru. Construction centers on preserving heritage aesthetics while integrating modern luxury, central open courtyards (Thotti Mane), and sustainable rainwater architecture.',
    bylawAuthority: 'BBMP South-West / Basavanagudi Ward 154',
    farAndSetbacks: 'FAR 1.75. Tree preservation and aesthetic guidelines for traditional avenues.',
    soilAndFoundation: 'Hard red sandy loam over granite. SBC 220 kN/m².',
    waterAndBorewell: 'Comprehensive BWSSB Cauvery network.',
    popularStyles: ['Heritage Courtyard Revival (Thotti Mane)', 'Modern Chettinad-Infused Contemporary', 'Classic Teak & Stone Villa'],
    avgCostPerSqFt: { essential: 2100, executive: 2650, luxury: 3800 },
    keyLandmarks: ['Bull Temple (Nandi Temple)', 'Gandhi Bazaar', 'Bugle Rock Park', 'National College Circle'],
  },
  {
    name: 'Vijayanagar',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560040',
    tagline: 'Established Commercial-Residential Hub: Multi-Tier Homes',
    overview: 'Known for its vibrant commercial avenues and tranquil residential cross-roads. High demand for G+3 multi-generational duplexes with ground-floor rental units or commercial clinics.',
    bylawAuthority: 'BBMP West / Vijayanagar Division Ward 123',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks for 30x40 and 40x60 sites.',
    soilAndFoundation: 'Red loam over rock. SBC 200 kN/m².',
    waterAndBorewell: 'Cauvery connection fully operational.',
    popularStyles: ['Modern Multi-Story Duplex', 'Contemporary Urban Family Home'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3300 },
    keyLandmarks: ['Vijayanagar Metro Station', 'Attiguppe Junction', 'Maruti Mandir Circle'],
  },
  {
    name: 'Nagarbhavi',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560072',
    tagline: 'Educational Hub: Scenic Hill-View Architectural Villas',
    overview: 'Adjacent to Bangalore University and National Law School. Rolling hilly terrain allows stepped terraces, basement entertainment lounges, and expansive contemporary 4BHK villas.',
    bylawAuthority: 'BBMP West & BDA Western Corridor',
    farAndSetbacks: 'FAR 1.75. Stepped terrain requires precise site contour surveying.',
    soilAndFoundation: 'Granite rock outcroppings. SBC 230–250 kN/m². Exceptional structural stability.',
    waterAndBorewell: 'Borewells 550–700 ft. Cauvery water expanding.',
    popularStyles: ['Hillside Contemporary Villa', 'Modern University View Duplex'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3250 },
    keyLandmarks: ['National Law School of India University (NLSIU)', 'Nagarbhavi BDA Complex', 'Bangalore University Jnana Bharathi'],
  },
  {
    name: 'Yeshwanthpur',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560022',
    tagline: 'Major Transit & Commercial Hub: Industrial Lofts & Modern Duplexes',
    overview: 'Convergence of railway, metro, and arterial highway. Builds demand heavy acoustic insulation, stilt commercial parking, and modern high-yield residential floors.',
    bylawAuthority: 'BBMP West / Ward 37',
    farAndSetbacks: 'FAR up to 2.25 on major wide roads.',
    soilAndFoundation: 'Dense red clayey sand. SBC 200 kN/m².',
    waterAndBorewell: 'Cauvery water connection active.',
    popularStyles: ['Modern Industrial Loft Duplex', 'Contemporary Urban Multi-Story'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3200 },
    keyLandmarks: ['Yeshwanthpur Railway Station', 'APMC Yard', 'Taj Yeshwantpur'],
  },
  {
    name: 'Mahalakshmi Layout',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560086',
    tagline: 'Hill-Temple Suburb: Vaastu-Aligned Family Residences',
    overview: 'Home to the famous Mahalakshmi Temple. Scenic elevated layout with cool breezes. Ideal for 3-story Vaastu-compliant family homes with rooftop temple-view gazebos.',
    bylawAuthority: 'BBMP West / Ward 68',
    farAndSetbacks: 'FAR 1.75. Standard setbacks.',
    soilAndFoundation: 'Rocky granite base. SBC 230 kN/m².',
    waterAndBorewell: 'BWSSB Cauvery network active.',
    popularStyles: ['Traditional Vaastu Villa', 'Modern Granite-Clad Duplex'],
    avgCostPerSqFt: { essential: 1850, executive: 2350, luxury: 3300 },
    keyLandmarks: ['Mahalakshmi Layout Temple', 'Iskcon Link Road', 'Metro Station'],
  },
  {
    name: 'RR Nagar',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560098',
    tagline: 'Rajarajeshwari Nagar: Sprawling Green Villas & Tech Enclaves',
    overview: 'One of the most sought-after green residential suburbs in the West. Known for the grand Temple Arch and Global Village Tech Park. Builds feature large 4BHK/5BHK villas with solar net metering and courtyard gardens.',
    bylawAuthority: 'BBMP RR Nagar Zone Headquarters',
    farAndSetbacks: 'FAR 1.75. Wide layout roads allow hassle-free construction logistics.',
    soilAndFoundation: 'Granite bedrock at 6–10 ft. SBC 220–240 kN/m². Highly solid foundation ground.',
    waterAndBorewell: 'Borewells average 600–750 ft. Cauvery network established.',
    popularStyles: ['Modern Sprawling Villa', 'Vaastu-Aligned Contemporary Duplex', 'Mediterranean Chic'],
    avgCostPerSqFt: { essential: 1750, executive: 2250, luxury: 3150 },
    keyLandmarks: ['RR Nagar Temple Arch', 'Global Village Tech Park', 'BEML Layout', 'Rajarajeshwari Temple'],
  },
  {
    name: 'Kengeri',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560060',
    tagline: 'Metro Terminal Suburb: Satellite Town Villa Architecture',
    overview: 'Western terminus of the Purple Line metro. Rapid appreciation in BDA satellite layouts. Projects focus on cost-effective, high-quality 3BHK and 4BHK independent homes for commuting professionals.',
    bylawAuthority: 'BBMP RR Nagar & BDA Satellite Town',
    farAndSetbacks: 'FAR 1.75. Simple approval processes.',
    soilAndFoundation: 'Red gravelly clay. SBC 200 kN/m².',
    waterAndBorewell: 'Borewells 650 ft. Rainwater harvesting mandatory.',
    popularStyles: ['Contemporary Budget Duplex', 'Modern 4BHK Family Villa'],
    avgCostPerSqFt: { essential: 1650, executive: 2100, luxury: 2900 },
    keyLandmarks: ['Kengeri Metro Terminal', 'Kengeri Satellite Town BDA Complex', 'Mysore Road Express Link'],
  },
  {
    name: 'Chandra Layout',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560040',
    tagline: 'Peaceful Planned Suburb between Vijayanagar & Nagarbhavi',
    overview: 'Quiet residential neighborhood with uniform plot divisions. Popular for multi-story family duplexes with ground-floor parking and open rooftop garden terraces.',
    bylawAuthority: 'BBMP West / Ward 131',
    farAndSetbacks: 'FAR 1.75. Standard 1.5m setbacks.',
    soilAndFoundation: 'Red sandy loam. SBC 195 kN/m².',
    waterAndBorewell: 'Active Cauvery water network.',
    popularStyles: ['Modern Urban Duplex', 'Contemporary Multi-Level Home'],
    avgCostPerSqFt: { essential: 1800, executive: 2300, luxury: 3200 },
    keyLandmarks: ['Chandra Layout Bus Stand', 'BDA Complex', 'Canara Bank Colony'],
  },
  {
    name: 'Peenya',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560058',
    tagline: 'Industrial Hub: Commercial Offices & Staff Residential Quarters',
    overview: 'One of Southeast Asia\'s largest industrial areas. Turnkey construction specializes in corporate offices, heavy-duty industrial warehouses, and executive residential duplexes.',
    bylawAuthority: 'BBMP Dasarahalli Zone / KIADB',
    farAndSetbacks: 'Industrial & commercial FAR up to 2.25. Heavy vehicle turning radius mandates.',
    soilAndFoundation: 'Heavy clay over rock. SBC 210 kN/m². Heavy-duty raft and industrial grade slab engineering.',
    waterAndBorewell: 'Industrial BWSSB network and deep borewells.',
    popularStyles: ['Industrial Modern Building', 'Durable Multi-Unit Residential'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['Peenya Industrial Area', 'Peenya Metro Station', 'Tumkur Road Expressway'],
  },
  {
    name: 'Magadi Road',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560023',
    tagline: 'Metro Arterial Corridor: Fast-Appreciating Duplexes',
    overview: 'Connecting city center to outer ring road along the metro line. Rapid residential transformation with new gated developments and high-yield multi-family homes.',
    bylawAuthority: 'BBMP West Zone',
    farAndSetbacks: 'FAR 1.75 – 2.0 along metro corridor.',
    soilAndFoundation: 'Red gravelly clay. SBC 195 kN/m².',
    waterAndBorewell: 'Cauvery water connection active.',
    popularStyles: ['Modern Transit-Oriented Duplex', 'Contemporary 3BHK Home'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['Magadi Road Metro Station', 'Tollgate Circle', 'Prasanna Theatre'],
  },
  {
    name: 'Mallathahalli',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560056',
    tagline: 'Lake View Haven adjacent to Bangalore University',
    overview: 'Peaceful lake-facing residential layout popular among academics and doctors. Ideal for open-terrace 4BHK family villas and independent duplexes.',
    bylawAuthority: 'BBMP RR Nagar Zone / Ward 130',
    farAndSetbacks: 'FAR 1.75. Lake buffer regulations observed.',
    soilAndFoundation: 'Red loam over granite. SBC 200 kN/m².',
    waterAndBorewell: 'Good groundwater table at 600 ft.',
    popularStyles: ['Lake-Facing Contemporary Villa', 'Modern Multi-Gen Home'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3050 },
    keyLandmarks: ['Mallathahalli Lake', 'Dr. Ambedkar Institute of Technology', 'Kengunte Circle'],
  },
  {
    name: 'Subramanyapura',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560061',
    tagline: 'Green Western Fringe: Quiet Independent Living',
    overview: 'Connecting Banashankari 5th Stage to Uttarahalli. Peaceful neighborhood for families building custom independent homes away from city congestion.',
    bylawAuthority: 'BBMP South-West / Ward 184',
    farAndSetbacks: 'FAR 1.75. Standard bylaws.',
    soilAndFoundation: 'Firm red soil. SBC 200 kN/m².',
    waterAndBorewell: 'Borewells 650 ft.',
    popularStyles: ['Traditional Family Duplex', 'Modern 3BHK Villa'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 2950 },
    keyLandmarks: ['Subramanyapura Lake', 'Gubbalala Gate', 'Vasanthapura Temple'],
  },
  {
    name: 'Ullal',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560056',
    tagline: 'Plotted Layout Frontier: Spacious Modern Villas',
    overview: 'Bordering Sir M Visvesvaraya Layout. Rapidly developing with large BDA plotted sites. High demand for modern architecture with double-height atriums and landscaped gardens.',
    bylawAuthority: 'BDA & BBMP RR Nagar Zone',
    farAndSetbacks: 'FAR 1.75. Excellent road infrastructure.',
    soilAndFoundation: 'Red gravelly loam. SBC 205 kN/m².',
    waterAndBorewell: 'Borewells average 650 ft.',
    popularStyles: ['Contemporary Sprawling Duplex', 'Modern Open-Plan Villa'],
    avgCostPerSqFt: { essential: 1700, executive: 2150, luxury: 3000 },
    keyLandmarks: ['Ullal Lake', 'SMV Layout 4th Block', 'Bangalore University Ring Road'],
  },
  {
    name: 'Sir MV Layout',
    zone: 'West Zone',
    zoneSlug: 'west',
    pincode: '560056',
    tagline: 'Sir M Visvesvaraya Layout: Model BDA Modern Suburb',
    overview: 'Named after Karnataka\'s legendary civil engineer. Planned with wide 40ft, 60ft, and 80ft roads across 9 blocks. Prime area for architect-designed turnkey residences and luxury duplexes.',
    bylawAuthority: 'BDA (Bangalore Development Authority) & BBMP',
    farAndSetbacks: 'FAR 1.75 – 2.0. Pristine BDA layout guidelines ensure clean setbacks and high open space.',
    soilAndFoundation: 'Red gravelly clay over granite bedrock. SBC 215 kN/m². Ideal structural foundation strata.',
    waterAndBorewell: 'Groundwater 650 ft. Cauvery line integration underway. Rainwater harvesting mandatory.',
    popularStyles: ['Modern Architectural Showcase Home', 'Contemporary 4BHK Duplex', 'Minimalist European Villa'],
    avgCostPerSqFt: { essential: 1750, executive: 2200, luxury: 3100 },
    keyLandmarks: ['SMV Layout 1st to 9th Blocks', 'Magadi Main Road Link', 'Bangalore University Campus'],
  },
];

export const allLocations: LocalityData[] = rawLocalities.map((loc) => {
  const slug = nameToSlug(loc.name);
  return {
    ...loc,
    slug,
    faqs: [
      {
        question: `What is the average cost to construct an independent house in ${loc.name}, Bengaluru?`,
        answer: `In ${loc.name}, turnkey residential construction typically ranges from ₹${loc.avgCostPerSqFt.essential.toLocaleString('en-IN')}/sq.ft for our Essential package up to ₹${loc.avgCostPerSqFt.luxury.toLocaleString('en-IN')}+/sq.ft for bespoke Luxury architectural builds. Final rates depend on soil foundation depth, structural design, and interior finishing choices.`,
      },
      {
        question: `How does Construction Buddy handle BBMP / BDA sanction drawings for ${loc.name}?`,
        answer: `All our blueprints are engineered strictly in accordance with ${loc.bylawAuthority} bylaws. We handle architectural floor plans, structural vetting, MEP layouts, and liaison documentation to ensure your plan approval and commencement certificate (CC) proceed without municipal delays.`,
      },
      {
        question: `What foundation type is required for plots in ${loc.name}?`,
        answer: `Plots in ${loc.name} typically feature ${loc.soilAndFoundation}. Our structural engineers conduct on-site soil testing to calculate the exact Safe Bearing Capacity (SBC) before designing isolated, combined, or raft footings with high-durability Fe550D TMT reinforcement.`,
      },
      {
        question: `Do you provide fixed-cost guarantees and penalty-backed handover in ${loc.name}?`,
        answer: `Yes. Every project in ${loc.name} is executed on a guaranteed fixed-cost roadmap with zero mid-construction price escalations, a 10-year structural warranty, and a penalty-backed handover timeline clearly defined in our client contract.`,
      },
    ],
  };
});

export function getAllLocations(): LocalityData[] {
  return allLocations;
}

export function getLocationBySlug(slug: string): LocalityData | undefined {
  return allLocations.find((loc) => loc.slug === slug);
}

export function getLocationsByZone(zoneSlug: string): LocalityData[] {
  return allLocations.filter((loc) => loc.zoneSlug === zoneSlug);
}

export function getNearbyLocations(slug: string, count = 4): LocalityData[] {
  const current = getLocationBySlug(slug);
  if (!current) return allLocations.slice(0, count);
  return allLocations
    .filter((loc) => loc.zoneSlug === current.zoneSlug && loc.slug !== current.slug)
    .slice(0, count);
}
